version: "3.9"

networks:
  inception:
    driver: bridge

volumes:
  mariadb_v:
    name: mariadb_v
    driver: local
    driver_opts:
      device: /home/btchiman/data/mariadb
      type: none
      o: bind
  wordpress_v:
    name: wordpress_v
    driver: local
    driver_opts:
      device: /home/btchiman/data/wordpress/
      type: none
      o: bind

services:
  nginx:
    build: ./requirements/nginx
    image: nginx_i
    container_name: nginx_c
    ports:
      - "443:443"
    env_file:
      - .env
    networks:
      - inception
    restart: on-failure
    volumes:
      - wordpress_v:/var/www/html
    depends_on:
      - wordpress

  mariadb:
    build: ./requirements/mariadb
    image: mariadb_i
    container_name: mariadb_c
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - mariadb_v:/var/lib/mysql
    restart: on-failure

  wordpress:
    build: ./requirements/wordpress
    image: wordpress_i
    container_name: wordpress_c
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - wordpress_v:/var/www/html
    restart: on-failure
    depends_on:
      - mariadb